#
# Automatically generated by script/rosedb_generate.pl on Thu Nov  7 09:27:16 2013
# --- DO NOT EDIT! ---
#

package MAuction::DB::Bid;

use strict;

use base qw(MAuction::DB::Object);

__PACKAGE__->meta->setup(
    table   => 'bids',

    columns => [
        id      => { type => 'serial', not_null => 1 },
        user_id => { type => 'integer', not_null => 1 },
        item_id => { type => 'integer', not_null => 1 },
        ts      => { type => 'timestamp', not_null => 1 },
        amount  => { type => 'numeric', not_null => 1, precision => 2, scale => 7 },
    ],

    primary_key_columns => [ 'id' ],

    foreign_keys => [
        item => {
            class       => 'MAuction::DB::Item',
            key_columns => { item_id => 'id' },
        },

        user => {
            class       => 'MAuction::DB::User',
            key_columns => { user_id => 'id' },
        },
    ],
);

1;

