#
# Automatically generated by script/rosedb_generate.pl on Thu Nov  7 09:27:16 2013
# --- DO NOT EDIT! ---
#

package MAuction::DB::Item;

use strict;

use base qw(MAuction::DB::Object);

__PACKAGE__->meta->setup(
    table   => 'items',

    columns => [
        id            => { type => 'serial', not_null => 1 },
        user_id       => { type => 'integer', not_null => 1 },
        name          => { type => 'text', not_null => 1 },
        description   => { type => 'text', not_null => 1 },
        bid_increment => { type => 'numeric', not_null => 1, precision => 2, scale => 5 },
        bid_min       => { type => 'numeric', not_null => 1, precision => 2, scale => 7 },
        start_ts      => { type => 'timestamp', not_null => 1 },
        end_ts        => { type => 'timestamp', not_null => 1 },
    ],

    primary_key_columns => [ 'id' ],

    foreign_keys => [
        user => {
            class       => 'MAuction::DB::User',
            key_columns => { user_id => 'id' },
        },
    ],

    relationships => [
        bids => {
            class      => 'MAuction::DB::Bid',
            column_map => { id => 'item_id' },
            type       => 'one to many',
        },
    ],
);

1;

