#
# Automatically generated by script/rosedb_generate.pl on Thu Nov  7 09:27:16 2013
# --- DO NOT EDIT! ---
#

package MAuction::DB::User;

use strict;

use base qw(MAuction::DB::Object);

__PACKAGE__->meta->setup(
    table   => 'users',

    columns => [
        id       => { type => 'serial', not_null => 1 },
        username => { type => 'text', not_null => 1 },
    ],

    primary_key_columns => [ 'id' ],

    unique_key => [ 'username' ],

    relationships => [
        bids => {
            class      => 'MAuction::DB::Bid',
            column_map => { id => 'user_id' },
            type       => 'one to many',
        },

        items => {
            class      => 'MAuction::DB::Item',
            column_map => { id => 'user_id' },
            type       => 'one to many',
        },
    ],
);

1;

