#
# Automatically generated by script/rosedb_generate.pl on Thu Nov  7 09:27:16 2013
# --- DO NOT EDIT! ---
#

package MAuction::DB::Bid::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use MAuction::DB::Bid;

sub object_class { 'MAuction::DB::Bid' }

__PACKAGE__->make_manager_methods('bids');

1;

