#
# Automatically generated by script/rosedb_generate.pl on Thu Nov  7 09:27:16 2013
# --- DO NOT EDIT! ---
#

package MAuction::DB::User::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use MAuction::DB::User;

sub object_class { 'MAuction::DB::User' }

__PACKAGE__->make_manager_methods('users');

1;

