#
# Automatically generated by script/rosedb_generate.pl on Thu Nov  7 09:27:16 2013
# --- DO NOT EDIT! ---
#

package MAuction::DB::Item::Manager;

use strict;

use base qw(Rose::DB::Object::Manager);

use MAuction::DB::Item;

sub object_class { 'MAuction::DB::Item' }

__PACKAGE__->make_manager_methods('items');

1;

